title: Muhammad Hafidz Roihan # your name (or website title) here
logo: "/images/foto_diri.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Final year Post-Harvest Technology student from Bandung Institute Technology.
  <br><br>
  Interested in data analytics, especially supply chain analytics.
  <br><br>
  <a href="https://www.linkedin.com/in/muhammad-hafidz-roihan-05081a195/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-QQ74YF25WM # your Google Analytics tracking ID here
